service: api

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  create-submission:
    handler: bin/dummy
    events:
      - http:
          path: submissions
          method: post
  list-submissions:
    handler: bin/dummy
    events:
      - http:
          path: submissions
          method: get
  get-submission:
    handler: bin/dummy
    events:
      - http:
          path: submissions/{id}
          method: get
          request:
            parameters:
              paths:
              id: true
  create-metadata:
    handler: bin/dummy
    events:
      - http:
          path: submissions/{id}/metadata
          method: post
          request:
            parameters:
              paths:
              id: true
  list-metadata:
    handler: bin/dummy
    events:
      - http:
          path: submissions/{id}/metadata
          method: get
          request:
            parameters:
              paths:
              id: true
  get-metadata:
    handler: bin/dummy
    events:
      - http:
          path: submissions/{id}/metadata/{uuid}
          method: get
          request:
            parameters:
              paths:
                id: true
                uuid: true
  validate:
    handler: bin/validate
    events:
    - http:
        path: validate
        method: post

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: submissions
        AttributeDefinitions:
          - AttributeName: owner
            AttributeType: S
          - AttributeName: submission_id
            AttributeType: S
        KeySchema:
          - AttributeName: owner
            KeyType: HASH
          - AttributeName: submission_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: lambda-dynamodb-submissions
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: arn:aws:dynamodb:*:*:table/submissions
        Roles:
          - Ref: IamRoleLambdaExecution